import {
  nbaTeamCodes,
  type Category,
  type CategoryAnswer,
  type NbaTeamCode,
} from "@/lib/category-types";
import { toStableAnswerId } from "@/lib/normalize";

export const nbaRosters = {
  ATL: [
    "CJ McCollum",
    "Jalen Johnson",
    "Dyson Daniels",
    "Onyeka Okongwu",
    "Nickeil Alexander-Walker",
    "Corey Kispert",
    "Zaccharie Risacher",
    "Buddy Hield",
    "Aaron Wiggins",
    "Devin Carter",
  ],
  BOS: [
    "Jayson Tatum",
    "Paul George",
    "Derrick White",
    "Mitchell Robinson",
    "Sam Hauser",
    "Payton Pritchard",
    "Hugo Gonzalez",
    "Luka Garza",
    "Baylor Scheierman",
    "Neemias Queta",
  ],
  BKN: [
    "Michael Porter Jr.",
    "Julius Randle",
    "Terance Mann",
    "Egor Demin",
    "Day'Ron Sharpe",
    "Noah Clowney",
    "Moritz Wagner",
    "Nolan Traore",
    "Drake Powell",
    "Ben Saraf",
  ],
  CHA: [
    "Naz Reid",
    "Grayson Allen",
    "Brandon Miller",
    "Grant Williams",
    "Dorian Finney-Smith",
    "Coby White",
    "Royce O'Neale",
    "Kon Knueppel",
    "Tidjane Salaun",
    "Tre Mann",
  ],
  CHI: [
    "Josh Giddey",
    "Nic Claxton",
    "Norman Powell",
    "Zach Collins",
    "Patrick Williams",
    "Isaac Okoro",
    "Jalen Smith",
    "Tre Jones",
    "Rob Dillingham",
    "Matas Buzelis",
  ],
  CLE: [
    "Donovan Mitchell",
    "Evan Mobley",
    "James Harden",
    "Jarrett Allen",
    "Max Strus",
    "Dennis Schroder",
    "Sam Merrill",
    "Jaylon Tyson",
    "Nae'Qwan Tomlin",
    "Craig Porter Jr.",
  ],
  DAL: [
    "Kyrie Irving",
    "P.J. Washington",
    "Klay Thompson",
    "Daniel Gafford",
    "Santi Aldama",
    "Cooper Flagg",
    "Caleb Martin",
    "Naji Marshall",
    "Max Christie",
    "Dereck Lively II",
  ],
  DEN: [
    "Nikola Jokić",
    "Jamal Murray",
    "Aaron Gordon",
    "Cameron Johnson",
    "Christian Braun",
    "Zeke Nnaji",
    "Julian Strawther",
    "Peyton Watson",
    "DaRon Holmes II",
    "Jalen Pickett",
  ],
  DET: [
    "Cade Cunningham",
    "John Collins",
    "Kevin Huerter",
    "Duncan Robinson",
    "Isaiah Joe",
    "Ausar Thompson",
    "Ronald Holland II",
    "Jalen Duren",
    "Paul Reed",
    "Daniss Jenkins",
  ],
  GSW: [
    "Stephen Curry",
    "Jimmy Butler III",
    "Kristaps Porzingis",
    "Draymond Green",
    "Moses Moody",
    "Al Horford",
    "Brandin Podziemski",
    "Gui Santos",
    "De'Anthony Melton",
    "Charles Bassey",
  ],
  HOU: [
    "Kevin Durant",
    "Alperen Sengun",
    "Fred VanVleet",
    "Jabari Smith Jr.",
    "Bogdan Bogdanović",
    "Steven Adams",
    "Amen Thompson",
    "Reed Sheppard",
    "Clint Capela",
    "Tari Eason",
  ],
  IND: [
    "Pascal Siakam",
    "Tyrese Haliburton",
    "Ivica Zubac",
    "Andrew Nembhard",
    "Obi Toppin",
    "Aaron Nesmith",
    "T.J. McConnell",
    "Jarace Walker",
    "Kelly Oubre Jr.",
    "Ben Sheppard",
  ],
  LAC: [
    "Kawhi Leonard",
    "Darius Garland",
    "Rui Hachimura",
    "Derrick Jones Jr.",
    "Bennedict Mathurin",
    "Brook Lopez",
    "Isaiah Jackson",
    "Kris Dunn",
    "Yanic Konan Niederhauser",
    "Jordan Miller",
  ],
  LAL: [
    "Luka Dončić",
    "LeBron James",
    "Collin Sexton",
    "Austin Reaves",
    "Jarred Vanderbilt",
    "Quentin Grimes",
    "Kevon Looney",
    "Ziaire Williams",
    "Jake LaRavia",
    "Walker Kessler",
  ],
  MEM: [
    "Jerami Grant",
    "Kentavious Caldwell-Pope",
    "Isaiah Stewart",
    "Ty Jerome",
    "Taylor Hendricks",
    "Zach Edey",
    "Cedric Coward",
    "D'Angelo Russell",
    "Kris Murray",
    "Walter Clayton Jr.",
  ],
  MIA: [
    "Giannis Antetokounmpo",
    "Bam Adebayo",
    "Andrew Wiggins",
    "Nikola Jović",
    "Bobby Portis",
    "Davion Mitchell",
    "Simone Fontecchio",
    "Dru Smith",
    "Tim Hardaway Jr.",
    "Pelle Larsson",
  ],
  MIL: [
    "Tyler Herro",
    "Myles Turner",
    "Kyle Kuzma",
    "Caris LeVert",
    "AJ Green",
    "Ousmane Dieng",
    "Jaime Jaquez Jr.",
    "Kevin Porter Jr.",
    "Kel'el Ware",
    "Ryan Rollins",
  ],
  MIN: [
    "Anthony Edwards",
    "LaMelo Ball",
    "Rudy Gobert",
    "Jaden McDaniels",
    "Josh Green",
    "Donte DiVincenzo",
    "Trey Lyles",
    "Ayo Dosunmu",
    "Joan Beringer",
    "Terrence Shannon Jr.",
  ],
  NOP: [
    "Zion Williamson",
    "Jordan Poole",
    "Dejounte Murray",
    "Trey Murphy III",
    "Herbert Jones",
    "Jeremiah Fears",
    "Jordan Hawkins",
    "Saddiq Bey",
    "Derik Queen",
    "Yves Missi",
  ],
  NYK: [
    "Karl-Anthony Towns",
    "OG Anunoby",
    "Jalen Brunson",
    "Mikal Bridges",
    "Josh Hart",
    "Andre Drummond",
    "Jose Alvarado",
    "Miles McBride",
    "Pacome Dadiet",
    "Jordan Clarkson",
  ],
  OKC: [
    "Chet Holmgren",
    "Jalen Williams",
    "Shai Gilgeous-Alexander",
    "Isaiah Hartenstein",
    "Alex Caruso",
    "Luguentz Dort",
    "Jaylin Williams",
    "Cason Wallace",
    "Kenrich Williams",
    "Nikola Topić",
  ],
  ORL: [
    "Franz Wagner",
    "Paolo Banchero",
    "Desmond Bane",
    "Jalen Suggs",
    "Nikola Vučević",
    "Wendell Carter Jr.",
    "Jonathan Isaac",
    "Anthony Black",
    "Goga Bitadze",
    "Tristan da Silva",
  ],
  PHI: [
    "Joel Embiid",
    "Jaylen Brown",
    "Tyrese Maxey",
    "Anfernee Simons",
    "VJ Edgecombe",
    "Dean Wade",
    "Dominick Barlow",
    "Trendon Watford",
    "Jabari Walker",
    "Justin Edwards",
  ],
  PHX: [
    "Devin Booker",
    "Jalen Green",
    "Miles Bridges",
    "Dillon Brooks",
    "Luke Kennard",
    "Khaman Maluach",
    "Mark Williams",
    "Haywood Highsmith",
    "Ryan Dunn",
    "Jamaree Bouyea",
  ],
  POR: [
    "Ja Morant",
    "Jrue Holiday",
    "Shaedon Sharpe",
    "Toumani Camara",
    "Scoot Henderson",
    "Damian Lillard",
    "Robert Williams III",
    "Deni Avdija",
    "Donovan Clingan",
    "Yang Hansen",
  ],
  SAC: [
    "Zach LaVine",
    "Domantas Sabonis",
    "De'Andre Hunter",
    "Keegan Murray",
    "Malik Monk",
    "Nique Clifford",
    "Jonathan Mogbo",
    "Dylan Cardwell",
    "Maxime Raynaud",
    "Precious Achiuwa",
  ],
  SAS: [
    "De'Aaron Fox",
    "Devin Vassell",
    "Tobias Harris",
    "Harrison Barnes",
    "Keldon Johnson",
    "Victor Wembanyama",
    "Dylan Harper",
    "Luke Kornet",
    "Stephon Castle",
    "Carter Bryant",
  ],
  TOR: [
    "Scottie Barnes",
    "Brandon Ingram",
    "Immanuel Quickley",
    "RJ Barrett",
    "Jakob Poeltl",
    "Gradey Dick",
    "Collin Murray-Boyles",
    "Ja'Kobe Walter",
    "Trayce Jackson-Davis",
    "Jamal Shead",
  ],
  UTA: [
    "Jaren Jackson Jr.",
    "Lauri Markkanen",
    "Jusuf Nurkić",
    "Ace Bailey",
    "Josh Okogie",
    "Keyonte George",
    "John Konchar",
    "Cody Williams",
    "Brice Sensabaugh",
    "Svi Mykhailiuk",
  ],
  WAS: [
    "Anthony Davis",
    "Trae Young",
    "Khris Middleton",
    "Alex Sarr",
    "Bilal Coulibaly",
    "Tre Johnson",
    "Deandre Ayton",
    "Cam Whitmore",
    "Bub Carrington",
    "Will Riley",
  ],
} as const satisfies Record<NbaTeamCode, readonly string[]>;

const manualAliases: Readonly<Record<string, readonly string[]>> = {
  "Anthony Davis": ["AD"],
  "Anthony Edwards": ["Ant"],
  "Bam Adebayo": ["Bam"],
  "CJ McCollum": ["CJ"],
  "D'Angelo Russell": ["DLo", "D-Lo"],
  "Giannis Antetokounmpo": ["Giannis"],
  "Ja Morant": ["Ja"],
  "Karl-Anthony Towns": ["KAT"],
  "Kentavious Caldwell-Pope": ["KCP"],
  "Michael Porter Jr.": ["MPJ"],
  "Nickeil Alexander-Walker": ["NAW"],
  "Nikola Jokić": ["Joker"],
  "OG Anunoby": ["OG"],
  "Paul George": ["PG13", "PG-13"],
  "Shai Gilgeous-Alexander": ["SGA"],
  "Stephen Curry": ["Steph"],
  "Trae Young": ["Trae"],
  "Victor Wembanyama": ["Wemby"],
};

const nbaTeamColors = {
  ATL: ["#E03A3E", "#C1D32F"], BOS: ["#007A33", "#BA9653"], BKN: ["#000000", "#777777"],
  CHA: ["#1D1160", "#00788C"], CHI: ["#CE1141", "#111111"], CLE: ["#860038", "#FDBB30"],
  DAL: ["#00538C", "#B8C4CA"], DEN: ["#0E2240", "#FEC524"], DET: ["#C8102E", "#1D42BA"],
  GSW: ["#1D428A", "#FFC72C"], HOU: ["#CE1141", "#C4CED4"], IND: ["#002D62", "#FDBB30"],
  LAC: ["#C8102E", "#1D428A"], LAL: ["#552583", "#FDB927"], MEM: ["#5D76A9", "#12173F"],
  MIA: ["#98002E", "#F9A01B"], MIL: ["#00471B", "#EEE1C6"], MIN: ["#0C2340", "#78BE20"],
  NOP: ["#0C2340", "#C8102E"], NYK: ["#006BB6", "#F58426"], OKC: ["#007AC1", "#EF3B24"],
  ORL: ["#0077C0", "#C4CED4"], PHI: ["#006BB6", "#ED174C"], PHX: ["#1D1160", "#E56020"],
  POR: ["#E03A3E", "#000000"], SAC: ["#5A2D81", "#63727A"], SAS: ["#000000", "#C4CED4"],
  TOR: ["#CE1141", "#000000"], UTA: ["#002B5C", "#F9A01B"], WAS: ["#002B5C", "#E31837"],
} as const satisfies Record<NbaTeamCode, readonly [string, string]>;

function buildNbaAnswers(): readonly CategoryAnswer[] {
  return nbaTeamCodes.flatMap((teamCode) =>
    nbaRosters[teamCode].map((canonicalText) => {
      const [primaryColor, secondaryColor] = nbaTeamColors[teamCode];
      return {
        id: `nba-${toStableAnswerId(canonicalText)}`,
        canonicalText,
        aliases: manualAliases[canonicalText] ?? [],
        visual: {
          kind: "text" as const,
          label: teamCode,
          accessibleLabel: `Team ${teamCode}`,
          primaryColor,
          secondaryColor,
        },
        groupIds: [teamCode],
        teamCode,
      };
    }),
  );
}

export const currentNbaPlayersCategory: Category = {
  slug: "current-nba-players",
  version: 1,
  snapshotDate: "2026-07-15",
  title: "Current NBA players",
  prompt: "How many NBA players can you name?",
  timeLimitSeconds: 90,
  inputLabel: "Type an NBA player’s name",
  inputPlaceholder: "Type a full name or unique last name…",
  sourceLabel: "NBA roster · July 15, 2026",
  coverage: {
    title: "Team coverage",
    itemLabel: "NBA teams",
    groups: nbaTeamCodes.map((teamCode) => ({ id: teamCode, label: teamCode })),
  },
  answers: buildNbaAnswers(),
};
